# Generated by Django 5.0 on 2025-04-17 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("useful", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypesBeneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tipo de Beneficiário"
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Beneficiário",
                "verbose_name_plural": "Tipos de Beneficiários",
                "ordering": ["type"],
            },
        ),
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nome do beneficiário"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(max_length=15, unique=True, verbose_name="CPF"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Endereço do beneficiário",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Número"
                    ),
                ),
                (
                    "phone_1",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Telefone Principal",
                    ),
                ),
                (
                    "phone_2",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Telefone Secundário",
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "crassOrigin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crass_origin",
                        to="useful.crass",
                        verbose_name="CRASS de Origem",
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="useful.neighborhood",
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "typesBeneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="typebeneficiary",
                        to="beneficiaries.typesbeneficiary",
                        verbose_name="Tipo de beneficiário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficiário",
                "verbose_name_plural": "Beneficiários",
                "ordering": ["name"],
            },
        ),
    ]
