# Generated by Django 5.0 on 2025-04-14 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0001_initial"),
        ("useful", "0003_crass"),
    ]

    operations = [
        migrations.AlterField(
            model_name="beneficiary",
            name="cpf",
            field=models.CharField(max_length=15, unique=True, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="beneficiary",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="beneficiary",
                to="useful.neighborhood",
                verbose_name="Bairro",
            ),
        ),
    ]
