# Generated by Django 5.0 on 2025-08-19 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "beneficiaries",
            "0002_beneficiary_complement_alter_beneficiary_address_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TypesEthnicity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Raça/Etnia"
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Raça/Etnia",
                "verbose_name_plural": "Raças/Etnias",
                "ordering": ["type"],
            },
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="ethnicty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="beneficiaries.typesethnicity",
                verbose_name="Raça/Etnia",
            ),
        ),
    ]
