# Generated by Django 5.0 on 2025-04-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_entry", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation_entry",
            options={
                "ordering": ["name"],
                "verbose_name": "Cadastrar Entrada",
                "verbose_name_plural": "Cadastrar Entradas",
            },
        ),
        migrations.AlterField(
            model_name="donation_entry",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Endereço"
            ),
        ),
    ]
