# Generated by Django 5.0 on 2025-04-21 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_entry", "0001_initial"),
        ("products", "0002_remove_product_is_compound"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonatedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField(verbose_name="Quantidade")),
                (
                    "acronym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unit",
                        to="products.acronym",
                        verbose_name="Unidade de Medida",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_item",
                        to="products.category",
                        verbose_name="Categoria do Produto",
                    ),
                ),
                (
                    "donation_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donated_items",
                        to="donation_entry.donation_entry",
                        verbose_name="Entrada de Doação",
                    ),
                ),
                (
                    "item_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product",
                        to="products.product",
                        verbose_name="Nome do Item",
                    ),
                ),
            ],
        ),
    ]
