# Generated by Django 5.0 on 2025-04-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donation_entry", "0002_alter_donation_entry_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="donation_entry", name="crassOrigin",),
    ]
