# Generated by Django 5.0 on 2025-04-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_entry", "0002_donateditem"),
    ]

    operations = [
        migrations.AddField(
            model_name="donateditem",
            name="observation",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Observação"
            ),
        ),
    ]
