# Generated by Django 5.0 on 2025-04-21 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_entry", "0003_remove_donation_entry_crassorigin"),
        ("institutions", "0006_alter_institution_neighborhood"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation_entry",
            options={
                "ordering": ["id"],
                "verbose_name": "Cadastrar Entrada",
                "verbose_name_plural": "Cadastrar Entradas",
            },
        ),
        migrations.AlterField(
            model_name="donation_entry",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="institution",
                to="institutions.institution",
                verbose_name="Nome do Doador",
            ),
        ),
    ]
