# Generated by Django 5.0 on 2025-04-23 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donation_entry", "0004_alter_donateditem_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donateditem",
            options={
                "ordering": ["id"],
                "verbose_name": "Cadastrar Entrada",
                "verbose_name_plural": "Relatório de Entradas",
            },
        ),
        migrations.RemoveField(model_name="donateditem", name="acronym",),
        migrations.RemoveField(model_name="donateditem", name="category",),
    ]
