# Generated by Django 5.0 on 2025-04-25 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "donation_entry",
            "0005_alter_donateditem_options_remove_donateditem_acronym_and_more",
        ),
        ("products", "0002_remove_product_is_compound"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationDisposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField(verbose_name="Quantidade")),
                (
                    "observation",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "donation_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disposal_item",
                        to="donation_entry.donation_entry",
                        verbose_name="Descarte de Doação",
                    ),
                ),
                (
                    "item_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposal_product",
                        to="products.product",
                        verbose_name="Nome do Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cadastrar Entrada",
                "verbose_name_plural": "Descartes de Doações",
                "ordering": ["id"],
            },
        ),
    ]
