# Generated by Django 5.0 on 2025-04-29 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_entry", "0006_donationdisposal"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation_entry",
            name="type_donation",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "ENTRADA"),
                    ("DESCARTE", "DESCARTE"),
                    ("INVENTÁRIO", "INVENTÁRIO"),
                ],
                default="ENTRADA",
                max_length=20,
                verbose_name="Tipo de Lançamento",
            ),
        ),
    ]
