# Generated by Django 5.0 on 2025-04-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_entry", "0007_donation_entry_type_donation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation_entry",
            name="type_donation",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "ENTRADA"),
                    ("DESCARTE", "DESCARTE"),
                    ("INVENTÁRIO", "INVENTÁRIO"),
                ],
                max_length=20,
                verbose_name="Tipo de Lançamento",
            ),
        ),
    ]
