# Generated by Django 5.0 on 2025-04-29 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_entry", "0008_alter_donation_entry_type_donation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation_entry",
            name="date_of_contact",
            field=models.DateField(verbose_name="Data de Contato ou Lançamento"),
        ),
        migrations.AlterField(
            model_name="donation_entry",
            name="pick_up_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PERÍODO DA MANHÃ", "PERÍODO DA MANHÃ"),
                    ("PERÍODO DA TARDE", "PERÍODO DA TARDE"),
                    ("07:00", "07:00"),
                    ("08:00", "08:00"),
                    ("09:00", "09:00"),
                    ("10:00", "10:00"),
                    ("11:00", "11:00"),
                    ("12:00", "12:00"),
                    ("13:00", "13:00"),
                    ("14:00", "14:00"),
                    ("15:00", "15:00"),
                    ("16:00", "16:00"),
                    ("17:00", "17:00"),
                    ("18:00", "18:00"),
                ],
                max_length=20,
                null=True,
                verbose_name="Hora de Retirada",
            ),
        ),
        migrations.AlterField(
            model_name="donation_entry",
            name="type_donation",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "ENTRADA"),
                    ("DESCARTE", "DESCARTE"),
                    ("INVENTÁRIO", "INVENTÁRIO"),
                ],
                default="ENTRADA",
                max_length=20,
                verbose_name="Tipo de Lançamento",
            ),
        ),
        migrations.AlterField(
            model_name="donation_entry",
            name="withdrawal_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Retirada (Opcional)"
            ),
        ),
    ]
