# Generated by Django 5.0 on 2025-08-19 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donation_entry", "0009_alter_donation_entry_date_of_contact_and_more"),
        ("institutions", "0008_institution_active"),
        ("useful", "0003_alter_crass_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation_entry",
            name="registration_number",
            field=models.CharField(
                default="PADRÃO",
                editable=False,
                help_text="Número de registro único para a entrada de doação",
                max_length=20,
                unique=True,
                verbose_name="Número de Registro",
            ),
        ),
        migrations.AlterField(
            model_name="donation_entry",
            name="address",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Endereço (Opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="donation_entry",
            name="contact",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Contato (Opcional)"
            ),
        ),
        migrations.AlterField(
            model_name="donation_entry",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="institution",
                to="institutions.institution",
                verbose_name="Nome do Doador (Opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="donation_entry",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="useful.neighborhood",
                verbose_name="Bairro (Opcional)",
            ),
        ),
        migrations.AlterField(
            model_name="donation_entry",
            name="number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número (Opcional)"
            ),
        ),
        migrations.AlterField(
            model_name="donation_entry",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Telefone (Opcional)"
            ),
        ),
        migrations.AlterField(
            model_name="donation_entry",
            name="pick_up_time",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PERÍODO DA MANHÃ", "PERÍODO DA MANHÃ"),
                    ("PERÍODO DA TARDE", "PERÍODO DA TARDE"),
                    ("07:00", "07:00"),
                    ("08:00", "08:00"),
                    ("09:00", "09:00"),
                    ("10:00", "10:00"),
                    ("11:00", "11:00"),
                    ("12:00", "12:00"),
                    ("13:00", "13:00"),
                    ("14:00", "14:00"),
                    ("15:00", "15:00"),
                    ("16:00", "16:00"),
                    ("17:00", "17:00"),
                    ("18:00", "18:00"),
                ],
                max_length=20,
                null=True,
                verbose_name="Hora de Retirada (Opcional)",
            ),
        ),
    ]
