# Generated by Django 5.0 on 2025-04-21 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useful", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crass",
            options={
                "ordering": ["crassOrigin"],
                "verbose_name": "Nome do Cras",
                "verbose_name_plural": "Nomes dos Cras",
            },
        ),
        migrations.AlterField(
            model_name="crass",
            name="crassOrigin",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Nome do Cras"
            ),
        ),
        migrations.AlterField(
            model_name="crass",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crass_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Cras",
            ),
        ),
    ]
