# Generated by Django 5.0 on 2025-04-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useful", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="neighborhood",
            name="neighborhood",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Nome do Bairro"
            ),
        ),
    ]
