# Generated by Django 5.0 on 2025-04-23 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useful", "0002_alter_crass_options_alter_crass_crassorigin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="crass",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="crass_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário Cras",
            ),
        ),
    ]
