# Generated by Django 5.0 on 2025-04-14 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("useful", "0002_alter_neighborhood_neighborhood"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crassOrigin",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nome do Crass"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nome do Responsável",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={"verbose_name": "Nome do Crass", "ordering": ["crassOrigin"]},
        ),
    ]
