# Generated by Django 5.0 on 2025-05-28 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "beneficiaries",
            "0002_beneficiary_complement_alter_beneficiary_address_and_more",
        ),
        ("products", "0002_remove_product_is_compound"),
        ("useful", "0003_alter_crass_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation_exit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_contact",
                    models.DateField(verbose_name="Data de Contato ou Lançamento"),
                ),
                (
                    "document_id",
                    models.CharField(
                        max_length=15, verbose_name="Documento de Identificação"
                    ),
                ),
                ("address", models.CharField(max_length=255, verbose_name="Endereço")),
                ("number", models.CharField(max_length=10, verbose_name="Número")),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "phone_1",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Telefone Principal",
                    ),
                ),
                (
                    "phone_2",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Telefone Secundário",
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "cras_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cras_origin",
                        to="useful.crass",
                        verbose_name="Cras Origem",
                    ),
                ),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="name_beneficiary",
                        to="beneficiaries.beneficiary",
                        verbose_name="Nome do Beneficiário",
                    ),
                ),
                (
                    "nightborhood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="useful.neighborhood",
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "type_beneficiary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="type_beneficiary",
                        to="beneficiaries.typesbeneficiary",
                        verbose_name="Tipo de Beneficiário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saída de Doação",
                "verbose_name_plural": "Saídas de Doações",
                "ordering": ["date_of_contact"],
            },
        ),
        migrations.CreateModel(
            name="Donated_exit_item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveBigIntegerField(verbose_name="Quantidade")),
                (
                    "observation",
                    models.TextField(
                        blank=True, max_length=100, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "item_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_exit",
                        to="products.product",
                        verbose_name="Nome do Item",
                    ),
                ),
                (
                    "donation_exit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donated_exit_items",
                        to="outflow_of_donations.donation_exit",
                        verbose_name="Saída de Doação",
                    ),
                ),
            ],
        ),
    ]
