# Generated by Django 5.0 on 2025-06-03 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outflow_of_donations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="donation_exit",
            old_name="nightborhood",
            new_name="neighborhood",
        ),
    ]
