# Generated by Django 5.0 on 2025-08-19 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("outflow_of_donations", "0002_rename_nightborhood_donation_exit_neighborhood"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donated_exit_item",
            options={
                "ordering": ["id"],
                "verbose_name": "Saída de Doação - Itens",
                "verbose_name_plural": "Saídas de Doações - Itens",
            },
        ),
    ]
