# Generated by Django 5.0 on 2025-04-08 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("useful", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypesInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tipo de Instituição"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={"verbose_name": "Tipo de Instituição", "ordering": ["type"],},
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Nome da Instituição"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=255, verbose_name="Endereço da Instituição"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=50, verbose_name="Número da Instituição"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=255, verbose_name="Telefone da Instituição"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "neighborhood",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institution",
                        to="useful.neighborhood",
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "typesInstitution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="institution",
                        to="institutions.typesinstitution",
                        verbose_name="Tipo de Instituição",
                    ),
                ),
            ],
            options={"verbose_name": "Nome da Instituição", "ordering": ["name"],},
        ),
    ]
