# Generated by Django 5.0 on 2025-04-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="number",
            field=models.CharField(max_length=50, verbose_name="Número"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="phone",
            field=models.CharField(max_length=255, verbose_name="Telefone"),
        ),
    ]
