# Generated by Django 5.0 on 2025-04-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="email",
            field=models.EmailField(
                blank=True, max_length=255, null=True, unique=True, verbose_name="Email"
            ),
        ),
    ]
