# Generated by Django 5.0 on 2025-04-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_alter_institution_number_alter_institution_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institution",
            options={"ordering": ["name"], "verbose_name": "Instituição"},
        ),
        migrations.AddField(
            model_name="institution",
            name="cnpj",
            field=models.CharField(
                blank=True, max_length=15, null=True, unique=True, verbose_name="CNPJ"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="address",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Endereço da Instituição",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Número"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Telefone"
            ),
        ),
    ]
