# Generated by Django 5.0 on 2025-04-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0002_alter_institution_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institution",
            options={
                "ordering": ["name"],
                "verbose_name": "Cadastrar",
                "verbose_name_plural": "Cadastrar",
            },
        ),
        migrations.AlterModelOptions(
            name="typesinstitution",
            options={
                "ordering": ["type"],
                "verbose_name": "Tipo",
                "verbose_name_plural": "Tipos",
            },
        ),
        migrations.AlterField(
            model_name="institution",
            name="typesInstitution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="typesInstitution",
                to="institutions.typesinstitution",
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="typesinstitution",
            name="type",
            field=models.CharField(max_length=100, unique=True, verbose_name="Tipo"),
        ),
    ]
