# Generated by Django 5.0 on 2025-04-21 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0003_alter_institution_options_and_more"),
        ("useful", "0002_alter_crass_options_alter_crass_crassorigin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="neighborhood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="useful.neighborhood",
                verbose_name="Bairro",
            ),
        ),
    ]
