# Generated by Django 5.0 on 2025-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0004_alter_institution_neighborhood"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="contact",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Contato"
            ),
        ),
    ]
