# Generated by Django 5.0 on 2025-04-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0006_alter_institution_neighborhood"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="complement",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Complemento"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Endereço"
            ),
        ),
    ]
