# Generated by Django 5.0 on 2025-08-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0007_institution_complement_alter_institution_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
