# Generated by Django 5.0 on 2025-04-17 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acronym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acronym",
                    models.CharField(max_length=4, unique=True, verbose_name="Sigla"),
                ),
                (
                    "description",
                    models.CharField(max_length=100, verbose_name="Descrição"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sigla",
                "verbose_name_plural": "Siglas",
                "ordering": ["acronym"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Categoria"
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome do Produto"
                    ),
                ),
                (
                    "unit_quantity",
                    models.PositiveIntegerField(verbose_name="Quantidade Unitária"),
                ),
                (
                    "is_compound",
                    models.BooleanField(
                        default=False, verbose_name="É um produto composto?"
                    ),
                ),
                (
                    "compound_quantity",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantidade composta"
                    ),
                ),
                (
                    "observation",
                    models.TextField(
                        blank=True, max_length=255, null=True, verbose_name="Observação"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
                (
                    "acronym",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.acronym",
                        verbose_name="Sigla",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category",
                        to="products.category",
                        verbose_name="Categoria do Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "ordering": ["name"],
            },
        ),
    ]
