# Generated by Django 5.0 on 2025-04-08 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="institution", name="neighborhood",),
        migrations.RemoveField(model_name="institution", name="typesInstitution",),
        migrations.DeleteModel(name="Neighborhood",),
        migrations.DeleteModel(name="Institution",),
        migrations.DeleteModel(name="TypesInstitution",),
    ]
