# Generated by Django 5.0 on 2025-04-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="is_compound",),
    ]
