# Generated by Django 5.0 on 2025-08-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_product_is_compound"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="code",
            field=models.CharField(
                default="Null", editable=False, max_length=20, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="acronym",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit_quantity",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Quantidade Unitária"
            ),
        ),
    ]
