# Generated by Django 5.0 on 2025-04-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_institution_neighborhood_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acronym",
            name="acronym",
            field=models.CharField(max_length=255, unique=True, verbose_name="Sigla"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Nome da Categoria"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Nome do Produto"
            ),
        ),
    ]
