# Generated by Django 5.0 on 2025-04-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_acronym_acronym_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nome da Categoria"),
        ),
    ]
