# Generated by Django 5.0 on 2025-04-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acronym",
            name="acronym",
            field=models.CharField(max_length=255, verbose_name="Sigla"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nome do Produto"),
        ),
    ]
